services:
  - type: web
    name: bik-assistent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/gcloud-key.json
    secrets:
      - source: gcloud-key.json
        mountPath: /etc/secrets/gcloud-key.json
